[package]
name = "letmeknow"
version = "0.1.0"
authors = ["Dimitrios Glynos"]
edition = "2018"

[dependencies]
pcap = "^0.9.0"
packet = "^0.1.4"
chrono = "^0.4.31"
syslog = "^6.0.0"
twilio = "^1.0.0"
futures = "0.3"
tokio = {version = "^1.32.0", features = ["full"] }
configparser = "^3.0.0"
